; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
build_src_filter = 
	+<main.cpp>
	+<pi-communication-test.cpp>
	+<KalmanFilter.cpp>
	+<main_kalmantest.cpp>
	+<KalmanFilterGM.cpp>
	+<KalmanFilterWN.cpp>
lib_deps = 
	adafruit/Adafruit INA219 @ ^1.2.3
	adafruit/Adafruit Unified Sensor @ ^1.1.14
	Adafruit BMP280 Library
	adafruit/Adafruit BusIO @ ^1.14.1
	Wire
	adafruit/Adafruit BNO08x
	adafruit/Adafruit BNO055
	https://github.com/tonton81/SPISlave_T4.git
	hideakitai/ArduinoEigen@^0.3.2
	robtillaart/INA226
monitor_speed = 115200
