[env:teensy40]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli

; just for testing, TODO DELETE LATER
build_src_filter =
    +<main.cpp>
    +<pi-communication-test.cpp>
    
; Library dependencies
lib_deps =
    adafruit/Adafruit INA219 @ ^1.2.3        
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    Adafruit BMP280 Library
    adafruit/Adafruit BusIO @ ^1.14.1
    Wire
    adafruit/Adafruit BNO08x
    https://github.com/tonton81/SPISlave_T4.git

; Serial Monitor settings
monitor_speed = 115200
